# Generated by Django 5.1.1 on 2024-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', 'employees_create_groups_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_contact_person_number',
            field=models.CharField(max_length=10),
        ),
    ]
