# Generated by Django 5.1.3 on 2024-11-06 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryOtherField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Good_Work_Allowance_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Good_Work_Allowance_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('ABRY_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('ABRY_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Add_Bonus_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Add_Bonus_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Arrears_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Arrears_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Attnd_Award_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Attnd_Award_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Attnd_Incentive_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Attnd_Incentive_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Bonus_Allowance_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Bonus_Allowance_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Conveyance_Allowance_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Conveyance_Allowance_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Festival_Bonus_refund_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Festival_Bonus_refund_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Gratuity_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Gratuity_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Night_Allowance_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Night_Allowance_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Production_incentive_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Production_incentive_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Welding_Allowance_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Welding_Allowance_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_other_fields', to='employees.company')),
            ],
        ),
    ]
