# Generated by Django 5.1.1 on 2024-10-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_salary_advance_deduction_salary_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
