# Generated by Django 5.1.1 on 2024-09-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
