# Generated by Django 5.1.2 on 2024-10-11 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_mymodel_alter_salary_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_esic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_canteen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_advance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esic_applicable', models.BooleanField(default=False)),
                ('pf_applicable', models.BooleanField(default=False)),
                ('lwf_applicable', models.BooleanField(default=False)),
                ('pd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esic_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pf_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lwf_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_paid_from_account', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid_to_employee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_recovered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_left', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('column_1', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
