# Generated by Django 5.1.1 on 2024-09-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_code', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=15)),
                ('bill_number', models.CharField(max_length=50)),
                ('purchased_item', models.CharField(choices=[('Stationary', 'Stationary'), ('Furniture', 'Furniture'), ('Pantry', 'Pantry'), ('Miscellaneous', 'Miscellaneous')], max_length=255)),
                ('hsn_code', models.CharField(max_length=10)),
                ('date_of_purchase', models.DateField()),
                ('per_unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_bought', models.PositiveIntegerField()),
                ('gross_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('net_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
            ],
        ),
    ]
