# Generated by Django 5.1.1 on 2024-09-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_purchaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=4)),
                ('firm_code', models.CharField(max_length=4)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_address', models.TextField()),
                ('vendor_gst_number', models.CharField(max_length=20)),
                ('vendor_account_number', models.CharField(max_length=20)),
                ('vendor_ifsc_code', models.CharField(max_length=11)),
                ('vendor_contact_person_name', models.CharField(max_length=100)),
                ('vendor_contact_person_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Furniture', 'Furniture'), ('Pantry', 'Pantry'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchased_item',
            field=models.CharField(max_length=255),
        ),
    ]
