# Generated by Django 5.1.2 on 2024-10-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_salarytotals_staffsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalary',
            name='advance_given',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='advance_pending',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
