# Generated by Django 5.1.2 on 2024-10-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_staffsalary_advance_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalary',
            name='advance_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffsalary',
            name='advance_given',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffsalary',
            name='advance_pending',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
