# Generated by Django 5.1.1 on 2024-09-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_vendorinformation_purchaseitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
