# Generated by Django 5.1.1 on 2024-09-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_vendorinformation_purchaseitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default=0, max_length=4)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('company_address', models.TextField()),
                ('company_gst_number', models.CharField(max_length=20)),
                ('company_account_number', models.CharField(max_length=20)),
                ('company_ifsc_code', models.CharField(max_length=11)),
                ('company_contact_person_name', models.CharField(max_length=100)),
                ('company_contact_person_number', models.CharField(max_length=100)),
            ],
        ),
    ]
