# Generated by Django 5.1.1 on 2024-09-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
