# Generated by Django 5.1.2 on 2024-10-11 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_staffsalary_advance_deduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('advance_taken', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('staff_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='employees.staffsalary')),
            ],
        ),
    ]
