# Generated by Django 5.1.2 on 2024-10-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_advancetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancetransaction',
            name='paid_received_account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='paid_received_by',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
