# Generated by Django 5.1.2 on 2024-10-11 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_advancetransaction_paid_received_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancetransaction',
            name='account',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='column1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='company',
            field=models.CharField(blank=True, default='Shree Hanuman', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='ifsc_code',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='mode',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='month',
            field=models.CharField(default=datetime.datetime.now, max_length=20),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='nature',
            field=models.CharField(default='personal', max_length=100),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='paid_received',
            field=models.CharField(choices=[('paid', 'Paid'), ('received', 'Received')], default='paid', max_length=10),
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='serial_number',
            field=models.IntegerField(default=1),
        ),
    ]
