# Generated by Django 5.1.1 on 2024-10-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_salary_options'),
    ]

    operations = [
    ]
