# Generated by Django 5.1.2 on 2024-10-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_advancetransaction_account_advancetransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_preference',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
