# Generated by Django 5.1.2 on 2024-10-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_profile_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancetransaction',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='advancetransaction',
            name='nature',
            field=models.CharField(choices=[('personal', 'Personal'), ('office', 'Office Expense'), ('company', 'Company Expense')], default='personal', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffsalary',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
