# Generated by Django 5.1.2 on 2024-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='database',
            field=models.CharField(default='yada yada', max_length=255),
        ),
    ]
