# Generated by Django 5.1.2 on 2024-10-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_profile_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancetransaction',
            name='ifsc_code',
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='account_ifsc_code',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='advancetransaction',
            name='account',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='advancetransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='advancetransaction',
            name='month',
            field=models.CharField(default='October', max_length=20),
        ),
    ]
