# Generated by Django 5.1.2 on 2024-10-30 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_remove_advancetransaction_ifsc_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancetransaction',
            name='account_ifsc_code',
        ),
        migrations.AddField(
            model_name='advancetransaction',
            name='ifsc_code',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_bonus_formula',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_cab_deduction',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_contact_person_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_esic_code',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_esic_deduction_rule',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_ot_rule',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_pf_code',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_salary_component_type',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_service_charge_over_time',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_service_charge_salary',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_welfare_deduction_rule',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='advancetransaction',
            name='account',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advancetransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_account_number',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_contact_person_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_contact_person_number',
            field=models.CharField(default='0', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_gst_number',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_ifsc_code',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
