# Generated by Django 5.1.2 on 2024-10-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_remove_advancetransaction_account_ifsc_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_cab_deduction',
            new_name='company_pf_deduction',
        ),
    ]
