# Generated by Django 5.1.2 on 2024-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_rename_company_cab_deduction_company_company_pf_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='salary_status',
            field=models.CharField(choices=[('apply', 'Apply'), ('do_not_apply', 'Do Not Apply'), ('wait', 'Wait')], default='wait', max_length=20),
        ),
    ]
