# Generated by Django 5.1.2 on 2024-10-31 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_company_salary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='salary_status',
            field=models.CharField(choices=[('apply', 'Apply'), ('do_not_apply', 'Do Not Apply'), ('wait', 'Wait')], default='apply', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('apply', 'Apply'), ('do_not_apply', 'Do Not Apply'), ('wait', 'Wait')], default='apply', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='employees.company')),
            ],
        ),
    ]
