# Generated by Django 5.1.2 on 2024-11-02 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_remove_company_salary_status_company_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancetransaction',
            name='month',
            field=models.CharField(default='November', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='allowance',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='hra',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_head', models.CharField(max_length=20)),
                ('Basic_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('Basic_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Sr_All_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('Sr_All_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('DA_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('DA_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('HRA_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('HRA_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('TA_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('TA_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Med_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('Med_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Conv_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('Conv_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Wash_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('Wash_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Eff_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('Eff_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Other_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('Other_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Incentive_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('Incentive_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Bonus_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('Bonus_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Over_Time_rate_type', models.CharField(choices=[('Per Month', 'Per Month')], default='Per Month', max_length=20)),
                ('Over_Time_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_rules', to='employees.company')),
            ],
        ),
    ]
