# Generated by Django 5.1.2 on 2024-11-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_alter_advancetransaction_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrule',
            name='Basic_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='Bonus_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='Conv_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='DA_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='Eff_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='HRA_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='Incentive_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='Med_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='Other_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='Over_Time_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='Sr_All_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='TA_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='Wash_rate_type',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20),
        ),
    ]
