# Generated by Django 5.1.3 on 2024-11-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_remove_company_allowance_remove_company_hra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrule',
            name='standard_head',
        ),
    ]
