# Generated by Django 5.1.3 on 2024-11-07 04:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryOtherField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Good_Work_Allowance_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Good_Work_Allowance_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('ABRY_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('ABRY_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Add_Bonus_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Add_Bonus_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Arrears_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Arrears_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Attnd_Award_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Attnd_Award_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Attnd_Incentive_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Attnd_Incentive_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Bonus_Allowance_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Bonus_Allowance_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Conveyance_Allowance_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Conveyance_Allowance_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Festival_Bonus_refund_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Festival_Bonus_refund_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Gratuity_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Gratuity_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Night_Allowance_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Night_Allowance_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Production_incentive_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Production_incentive_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
                ('Welding_Allowance_rate_type', models.CharField(choices=[('Per Month', 'Per Month'), ('Per Day', 'Per Day')], default='Per Month', max_length=20)),
                ('Welding_Allowance_pay_type', models.CharField(choices=[('PayDay', 'PayDay'), ('OTHour', 'OTHour')], default='PayDay', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='company',
            name='allowance',
        ),
        migrations.RemoveField(
            model_name='company',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='salaryrule',
            name='standard_head',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_contact_person_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_contact_person_number',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_salary_component_type',
            field=models.CharField(choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Month', 'Month')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='salaryotherfield',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_other_fields', to='employees.company'),
        ),
    ]
