# Generated by Django 5.1.3 on 2024-11-13 10:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_employee_employee_status_employee_performance_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='canteen',
            new_name='conveyance',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='transport',
            new_name='sr_allowance',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='advance',
            new_name='travel_allowance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esic_contribution',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pf_contribution',
        ),
        migrations.AddField(
            model_name='employee',
            name='da',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='efficiency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_payable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='wash_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pay_mode',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('cash', 'Cash')], default='bank', max_length=50),
        ),
    ]
