# Generated by Django 5.1.3 on 2024-11-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_rename_canteen_employee_conveyance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='gst_number',
            new_name='organization_gst_number',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='cgst_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='igst_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='sgst_amount',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_gst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
