# Generated by Django 5.1.3 on 2024-11-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_rename_gst_number_purchaseitem_organization_gst_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinformation',
            name='firm_code',
        ),
        migrations.AddField(
            model_name='vendorinformation',
            name='vendor_address_district',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorinformation',
            name='vendor_address_pincode',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='vendorinformation',
            name='vendor_address_state',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorinformation',
            name='vendor_address',
            field=models.CharField(max_length=100),
        ),
    ]
