# Generated by Django 5.1.3 on 2024-11-13 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_remove_vendorinformation_firm_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorinformation',
            old_name='vendor_address_district',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='vendorinformation',
            old_name='vendor_address_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='vendorinformation',
            name='vendor_address_pincode',
        ),
        migrations.AddField(
            model_name='vendorinformation',
            name='pincode',
            field=models.CharField(default=0, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Pincode must be 6 digits.')]),
        ),
    ]
