# Generated by Django 5.1.3 on 2024-11-13 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_rename_vendor_address_district_vendorinformation_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinformation',
            name='pincode',
            field=models.CharField(default='000000', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Pincode must be 6 digits.')]),
        ),
    ]
