# Generated by Django 5.1.3 on 2024-11-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_alter_vendorinformation_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('full payment received', 'Full Payment Received'), ('part payment received', 'part Payment Received')], default='Full Payment Received', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='remark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_of_own_company',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_against_bill',
            field=models.CharField(max_length=5),
        ),
    ]
