# Generated by Django 5.1.3 on 2024-11-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_payment_payment_status_payment_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('full_payment_received', 'Full Payment Received'), ('part_payment_received', 'part Payment Received')], default='Full Payment Received', max_length=100),
        ),
    ]
