# Generated by Django 5.1.3 on 2024-11-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='order_by',
            field=models.CharField(default='Mohit', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='order_for',
            field=models.CharField(default='Mohit', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='po_numer',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_against_bill',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='bill_number',
            field=models.CharField(max_length=5),
        ),
    ]
