# Generated by Django 5.1.3 on 2024-11-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0038_purchaseitem_order_by_purchaseitem_order_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Furniture', 'Furniture'), ('Pantry', 'Pantry'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=25),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='organization_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='po_numer',
            field=models.CharField(blank=True, default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchased_item',
            field=models.CharField(max_length=50),
        ),
    ]
