# Generated by Django 5.1.3 on 2024-11-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0039_alter_purchaseitem_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='po_numer',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='payment_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('upi', 'UPI')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='payment_status',
            field=models.CharField(choices=[('full_payment_vendor', 'Full Payment Done'), ('part_payment_vendor', 'Part Payment Done'), ('unpaid_vendor', 'Payment Pending')], default='full_payment_vendor', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='po_number',
            field=models.CharField(blank=True, default='0000', max_length=5),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='remark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='order_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='order_for',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='total_gst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
