# Generated by Django 5.1.3 on 2024-11-15 12:40

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0040_remove_purchaseitem_po_numer_purchaseitem_payment_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.bill_upload_path),
        ),
    ]
