# Generated by Django 5.1.3 on 2024-12-16 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0041_purchaseitem_bill_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einvoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='bill_amount',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='cess',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='cess_non_adv',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='city',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='deduction_amount_1',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='deduction_amount_2',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='deduction_narration_1',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='deduction_narration_2',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='department',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='month',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='print_proprietor_name',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='site',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='st_cess',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='taxable',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='type',
        ),
        migrations.AddField(
            model_name='einvoice',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='cess_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='cgst_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='document_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='document_type',
            field=models.CharField(choices=[('Tax Invoice', 'Tax Invoice'), ('Credit Note', 'Credit Note'), ('Debit Note', 'Debit Note')], default='Tax Invoice', max_length=255),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='igst_on_intra',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='igst_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='legal_name',
            field=models.CharField(default='Your Organisation Name', max_length=255),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='location',
            field=models.CharField(default='Delhi', max_length=255),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='payment_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='phone_no',
            field=models.CharField(default='+9100000000', max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='place_of_supply',
            field=models.CharField(choices=[('KA', 'Karnataka'), ('MH', 'Maharashtra')], default='Delhi', max_length=255),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='reverse_charge',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='reverse_charge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='reverse_charge_gstin',
            field=models.CharField(default='00000000000', max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid GSTIN format.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[A-Z0-9]{1}[Z]{1}[A-Z0-9]{1}$')]),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='reverse_charge_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='reverse_charge_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='sgst_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='total_taxable_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='transaction_type',
            field=models.CharField(default='Regular', max_length=255),
        ),
        migrations.AlterField(
            model_name='advancetransaction',
            name='month',
            field=models.CharField(default='December', max_length=20),
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='category',
            field=models.CharField(choices=[('B2B', 'B2B'), ('SEZWP', 'SEZWP'), ('SEZOP', 'SEZOP'), ('EXPWP', 'EXPWP'), ('EXPWOP', 'EXPWOP'), ('DEXPW', 'DEXPW')], default='B2B', max_length=255),
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='gstin',
            field=models.CharField(default='00000000000', max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid GSTIN format.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[A-Z0-9]{1}[Z]{1}[A-Z0-9]{1}$')]),
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='pincode',
            field=models.CharField(default=0, max_length=6, validators=[django.core.validators.RegexValidator(message='Invalid PIN code format.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='state',
            field=models.CharField(choices=[('KA', 'Karnataka'), ('MH', 'Maharashtra')], default='Delhi', max_length=100),
        ),
    ]
