# Generated by Django 5.1.3 on 2024-12-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_remove_einvoice_address_remove_einvoice_bill_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EInvoice',
        ),
        migrations.AddField(
            model_name='salaryotherfield',
            name='add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='add',
            field=models.BooleanField(default=False),
        ),
    ]
