# Generated by Django 5.2.4 on 2025-07-06 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0046_auto_20250706_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoice',
            name='buyer_gstin',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[A-Z0-9]{1}[Z]{1}[A-Z0-9]{1}$', 'Invalid GSTIN format')]),
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='supplier_gstin',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[A-Z0-9]{1}[Z]{1}[A-Z0-9]{1}$', 'Invalid GSTIN format')]),
        ),
    ]
