# Generated by Django 5.2.4 on 2025-07-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0047_alter_einvoice_buyer_gstin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.CreateModel(
            name='BillTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text="Name for this template (e.g., 'Monthly Manpower Service')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this template')),
                ('default_hsn_code', models.CharField(default='998519', help_text='Default HSN code for manpower services', max_length=10)),
                ('esi_rate', models.DecimalField(decimal_places=2, default=3.25, help_text='ESI rate as percentage', max_digits=5)),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=6.0, help_text='Service charge rate as percentage', max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, help_text='CGST rate as percentage', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, help_text='SGST rate as percentage', max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='IGST rate as percentage', max_digits=5)),
                ('apply_esi', models.BooleanField(default=True, help_text='Apply ESI contribution')),
                ('apply_service_charge', models.BooleanField(default=True, help_text='Apply service charge')),
                ('apply_cgst_sgst', models.BooleanField(default=True, help_text='Apply CGST/SGST (for same state)')),
                ('apply_igst', models.BooleanField(default=False, help_text='Apply IGST (for different state)')),
                ('round_to_nearest', models.DecimalField(decimal_places=2, default=0.01, help_text='Round final amount to nearest value', max_digits=5)),
                ('is_default', models.BooleanField(default=False, help_text='Make this the default template')),
                ('is_active', models.BooleanField(default=True, help_text='Template is active and can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_templates', to='employees.company')),
            ],
            options={
                'verbose_name': 'Bill Template',
                'verbose_name_plural': 'Bill Templates',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'template_name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('bill_date', models.DateField()),
                ('client_name', models.CharField(max_length=200)),
                ('client_address', models.TextField()),
                ('client_gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('client_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('service_period_from', models.DateField()),
                ('service_period_to', models.DateField()),
                ('total_gross_wages', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_esi_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reference_document', models.CharField(blank=True, help_text='PO Number or reference', max_length=100, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=200, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bills', to='employees.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='employees.billtemplate')),
            ],
            options={
                'verbose_name': 'Service Bill',
                'verbose_name_plural': 'Service Bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='e.g., Production Incentive, Attendance Award', max_length=200)),
                ('hsn_code', models.CharField(default='998519', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='employees.servicebill')),
            ],
            options={
                'verbose_name': 'Service Bill Item',
                'verbose_name_plural': 'Service Bill Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
