# Generated by Django 5.2.4 on 2025-07-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0048_alter_profile_theme_preference_billtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
