# Generated by Django 5.2.4 on 2025-07-07 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0049_einvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='order_for',
            field=models.ForeignKey(blank=True, help_text='Vendor for this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.vendorinformation'),
        ),
    ]
