# Generated by Django 5.2.4 on 2025-07-07 12:11

import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0050_alter_purchaseitem_order_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_code', models.CharField(max_length=5)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_gst_number', models.CharField(max_length=15)),
                ('bill_number', models.CharField(max_length=5, unique=True)),
                ('po_number', models.CharField(blank=True, default='0000', max_length=5)),
                ('order_by', models.CharField(blank=True, default='', max_length=50)),
                ('date_of_purchase', models.DateField()),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=4)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=4)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('payment_status', models.CharField(choices=[('full_payment_vendor', 'Full Payment Done'), ('part_payment_vendor', 'Part Payment Done'), ('unpaid_vendor', 'Payment Pending')], default='full_payment_vendor', max_length=50)),
                ('payment_by', models.CharField(blank=True, default='', max_length=50)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('upi', 'UPI')], default='', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to=employees.models.bill_upload_path)),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_gst_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_net_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_for', models.ForeignKey(blank=True, help_text='Vendor for this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.vendorinformation')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_item', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Stationary', 'Stationary'), ('Furniture', 'Furniture'), ('Pantry', 'Pantry'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=25)),
                ('hsn_code', models.CharField(max_length=10)),
                ('per_unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_bought', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='employees.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Line Item',
                'verbose_name_plural': 'Purchase Line Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
