# Generated by Django 5.2.4 on 2025-07-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0049_alter_purchase_fields'),
        ('employees', '0051_create_purchase_tabular_models'),
    ]

    operations = [
    ]
