# Generated by Django 5.2.4 on 2025-07-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0052_merge_20250707_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
