# Generated by Django 5.2.4 on 2025-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0053_update_purchase_tax_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='purchaselineitem',
            name='category',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='order_by',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
