# Generated by Django 5.2.4 on 2025-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0055_purchaselineitem_cgst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far', max_digits=12),
        ),
    ]
