# Generated by Django 5.2.4 on 2025-07-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0056_purchase_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='account_detail',
            field=models.CharField(blank=True, default='', help_text='Account detail for payment', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(blank=True, default='', help_text='Transaction ID if any', max_length=100),
        ),
    ]
