# Generated by Django 5.2.4 on 2025-07-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0057_purchase_account_detail_purchase_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
