# Generated by Django 5.2.4 on 2025-07-10 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0058_alter_purchase_payment_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(default='0000', max_length=4)),
                ('site_name', models.CharField(default='', max_length=100)),
                ('site_address', models.CharField(default='', max_length=255)),
                ('site_contact_person_name', models.CharField(default='', max_length=100)),
                ('site_contact_person_number', models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('site_contact_person_email', models.EmailField(default='', max_length=100)),
                ('site_gst_number', models.CharField(default='0', max_length=20)),
                ('site_pf_code', models.CharField(default='0', max_length=20)),
                ('site_esic_code', models.CharField(default='0', max_length=20)),
                ('site_service_charge_salary', models.CharField(default='0', max_length=20)),
                ('site_service_charge_over_time', models.CharField(default='0', max_length=20)),
                ('site_account_number', models.CharField(default='0', max_length=20)),
                ('site_ifsc_code', models.CharField(default='0', max_length=11)),
                ('site_salary_component_type', models.CharField(choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Month', 'Month')], default='0', max_length=20)),
                ('site_ot_rule', models.CharField(default='0', max_length=20)),
                ('site_bonus_formula', models.CharField(default='0', max_length=20)),
                ('site_pf_deduction', models.CharField(default='0', max_length=20)),
                ('site_esic_deduction_rule', models.CharField(default='0', max_length=20)),
                ('site_welfare_deduction_rule', models.CharField(default='0', max_length=20)),
                ('settings', models.JSONField(default=dict)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
