# Generated by Django 5.2.4 on 2025-07-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0059_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_salary_component_type',
            field=models.CharField(choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Month', 'Month')], default='Month', max_length=20),
        ),
    ]
