# Generated by Django 5.2.4 on 2025-07-10 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0060_alter_site_site_salary_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_contact_person_number',
            field=models.CharField(default='0000000000', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
