# Generated by Django 5.2.4 on 2025-07-10 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0063_alter_site_options_remove_site_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='site',
            name='settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_account_number',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_bonus_formula',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_code',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_contact_person_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_contact_person_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_contact_person_number',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_esic_code',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_esic_deduction_rule',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_gst_number',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_ifsc_code',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_ot_rule',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_pf_code',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_pf_deduction',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_service_charge_over_time',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_service_charge_salary',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_welfare_deduction_rule',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorinformation',
            name='vendor_contact_person_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
