# Generated by Django 5.2.4 on 2025-07-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0064_site_currency_site_settings_site_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='settings',
        ),
    ]
