# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0065_remove_site_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='site',
            name='timezone',
        ),
    ]
