# Generated by Django 5.2.4 on 2025-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0067_alter_site_site_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='site_address',
        ),
        migrations.AddField(
            model_name='site',
            name='site_address_line1',
            field=models.CharField(default='', help_text='Address line 1', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='site_address_line2',
            field=models.CharField(blank=True, default='', help_text='Address line 2 (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='site_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='site_pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='site_state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
