# Generated by Django 4.2 on 2025-07-11 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0068_update_site_address_to_structured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebill',
            name='client_contact_person',
        ),
        migrations.RemoveField(
            model_name='servicebill',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='servicebill',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='servicebill',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='servicebill',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='servicebill',
            name='reference_document',
        ),
        migrations.RemoveField(
            model_name='servicebill',
            name='service_period_from',
        ),
        migrations.RemoveField(
            model_name='servicebill',
            name='service_period_to',
        ),
        migrations.RemoveField(
            model_name='servicebill',
            name='total_esi_contribution',
        ),
        migrations.RemoveField(
            model_name='servicebill',
            name='total_service_charge',
        ),
        migrations.RemoveField(
            model_name='servicebillitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='servicebillitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='servicebillitem',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='servicebillitem',
            name='unit_rate',
        ),
        migrations.AddField(
            model_name='servicebillitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='servicebill',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicebill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='servicebillitem',
            name='description',
            field=models.CharField(help_text='e.g., Manpower Supply', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicebillitem',
            name='hsn_code',
            field=models.CharField(max_length=10),
        ),
    ]
