# Generated by Django 4.2 on 2025-08-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0070_migrate_to_site_centric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesattendance',
            name='company',
        ),
        migrations.RemoveField(
            model_name='report',
            name='company',
        ),
        migrations.RemoveField(
            model_name='site',
            name='company',
        ),
        migrations.AddField(
            model_name='report',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employees.site'),
        ),
        migrations.AlterField(
            model_name='advancetransaction',
            name='month',
            field=models.CharField(default='August', max_length=20),
        ),
    ]
