# Generated by Django 4.2 on 2025-08-01 09:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0071_remove_employeesattendance_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='travel_allowance',
            new_name='transport',
        ),
        migrations.AddField(
            model_name='employee',
            name='canteen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
