# Generated by Django 4.2 on 2025-08-01 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0072_rename_travel_allowance_employee_transport_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billtemplate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='arrear',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyadvancetransaction',
            name='company',
        ),
        migrations.AddField(
            model_name='arrear',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.site'),
        ),
        migrations.AddField(
            model_name='billtemplate',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_templates', to='employees.site'),
        ),
        migrations.AddField(
            model_name='companyadvancetransaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.site'),
        ),
        migrations.AlterUniqueTogether(
            name='billtemplate',
            unique_together={('site', 'template_name')},
        ),
        migrations.RemoveField(
            model_name='billtemplate',
            name='company',
        ),
    ]
