# Generated by Django 4.2 on 2025-08-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0073_alter_billtemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='advance',
        ),
    ]
