# Generated by Django 4.2 on 2025-08-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0074_remove_salary_advance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebill',
            name='company',
        ),
        migrations.AddField(
            model_name='servicebill',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_bills', to='employees.site'),
        ),
    ]
